version: '3'

services:
  deeplearning_models:
    build: .
    image: deeplearning_models_image
    container_name: deeplearning_models_container
    # 共有メモリの設定
    shm_size: "20gb"
    # 作業ディレクトリの指定とマウント
    working_dir: /work
    volumes:
      - .:/work
      - /mnt/dataset:/dataset
      - /mnt/models:/models
    # 環境変数の設定
    environment:
      - PYTHONPATH=/work/dezero:/work/pytorch
    # ポートの指定と Jupyter Lab の起動
    ports:
      - "8888:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost
    # GPU を使うための設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [utility, compute, video]